# change the build directory to be within react's scope
project_structure:
    build: ./client/src/build

# set a custom mnemonic for the development network
networks:
  default: development
  development:
    cmd_settings:
      mnemonic: very unusual thrive report daring stereo pulp fabric alien poet alarm chaos

# enable output of development artifacts to load with react
dev_deployment_artifacts: true
